### ISSUE TITLE
Lid sometimes takes one time to open and close before it reacts

### ISSUE THREAD

**Issue by JakeRoggenbuck** [JakeRoggenbuck/auto-clock-speed#71]
ACS is supposed to set gov to powersave when the lid closes. This does happen but sometimes it takes one open/close before it works. This might have to do with the initial state of the lid set in daemon.rs.

**Comment by JakeRoggenbuck** [comment]
This still happens but it seems to be a hardware issue. My screen also goes dark only the first time and might stop the code from knowing the lid state. More research required.

**Comment by Camerooooon** [comment]
Im going to make the daemon set the corret performance state on startup instead of just defaulting to a certain value.

**Comment by Camerooooon** [comment]
Seems like this issue is potentially caused by the system sleeping and stopping ACS before it gets a chance to change the power state.

Try taking a look in `/etc/systemd/logind.conf` and uncomment and make `HandleLidSwitch=ignore`. Restart `systemd-logind` service then run ACS while checked out into #118 the ACS lid logic should now work properly but your screen won't turn off. This will ensure that your computer is not going to sleep and for sure using ACS's logic. If this works then having lid detection of ACS is kinda pointless. More testing is required and definitely needed.

**Comment by JakeRoggenbuck** [comment]
Yea, it looks like most laptops handle this by default, hm. Should we close the issue?
